"""The blind workspace: a throwaway directory holding only a small markdown index.

The agent CLI is started inside it, so at startup it sees no source code, just
the list of known repos and how to open one.
"""

from __future__ import annotations

import os
import shutil
import time
from pathlib import Path

from .config import Config, cache_dir
from .scan import Repo

CONTEXT_FILENAMES = ("AGENTS.md", "CLAUDE.md", "GEMINI.md")


def sessions_dir() -> Path:
    return cache_dir() / "sessions"


def _line(repo: Repo, with_markers: bool = True) -> str:
    desc = repo.description[:100].rstrip()
    extra = f" [{', '.join(repo.markers)}]" if with_markers and repo.markers else ""
    return f"- {repo.name}: {repo.path}{extra}" + (f" - {desc}" if desc else "")


def render_index(opened: list[Repo], closed: list[Repo], cfg: Config, linked: bool = False) -> str:
    lines = [
        "# Blind workspace (generated by blinders)",
        "",
        "This session started *blind*: this directory holds no source code, only this index.",
        "Do not guess file paths inside repos that are not opened.",
        "",
    ]
    if opened:
        where = "linked under this directory" if linked else "added to this session"
        lines += [f"## Opened repos ({where})"]
        lines += [_line(r) for r in opened]
        lines += [""]
    else:
        lines += ["## Opened repos", "- none yet", ""]
    shown = closed[: cfg.index_max_closed]
    lines += ["## Closed repos (known, not visible)"]
    lines += [_line(r, with_markers=False) for r in shown] or ["- none"]
    if len(closed) > len(shown):
        lines.append(f"- ... and {len(closed) - len(shown)} more (run `blind list`)")
    lines += [
        "",
        "## Opening a closed repo",
        "Ask the user to run `/add-dir <path>` (Claude Code) or `/directory add <path>` (Gemini CLI),",
        "or to restart with `blind run <cli> -r <repo-name>` (Codex, Mistral Vibe).",
        "",
    ]
    return "\n".join(lines)


def create_session(opened: list[Repo], closed: list[Repo], cfg: Config, link: bool = False) -> Path:
    root = sessions_dir()
    root.mkdir(parents=True, exist_ok=True)
    session = root / f"{time.strftime('%Y%m%d-%H%M%S')}-{os.getpid()}"
    session.mkdir()
    text = render_index(opened, closed, cfg, linked=link)
    for name in CONTEXT_FILENAMES:
        (session / name).write_text(text, encoding="utf-8")
    if link:
        for repo in opened:
            target = session / repo.name
            if not target.exists():
                target.symlink_to(repo.path, target_is_directory=True)
    return session


def prune_sessions(cfg: Config, everything: bool = False) -> int:
    root = sessions_dir()
    if not root.is_dir():
        return 0
    cutoff = time.time() - cfg.session_ttl_days * 86400
    removed = 0
    for entry in root.iterdir():
        try:
            if entry.is_dir() and not entry.is_symlink() and (everything or entry.stat().st_mtime < cutoff):
                shutil.rmtree(entry)  # never follows symlinks: removes links, not their targets
                removed += 1
        except OSError:
            continue
    return removed
