"""The blind workspace: a throwaway directory holding only a small markdown index.

The agent CLI is started inside it, so at startup it sees no source code, just
the list of known repos and how to open one.
"""

from __future__ import annotations

import json
import os
import shutil
import tempfile
import time
from pathlib import Path

from .config import Config, cache_dir
from .scan import Repo

CONTEXT_FILENAMES = ("AGENTS.md", "CLAUDE.md", "GEMINI.md")


def sessions_dir() -> Path:
    return cache_dir() / "sessions"


def _line(repo: Repo, why: str = "") -> str:
    desc = repo.description[:100].rstrip()
    tail = f" - {why}" if why else (f" - {desc}" if desc else "")
    return f"- {repo.name}: {repo.path}{tail}"


def render_index(
    opened: list[Repo],
    closed: list[Repo],
    cfg: Config,
    linked: bool = False,
    related: list | None = None,
    mcp_dropped: list[str] | None = None,
    cli: str = "<cli>",
    skills_dropped: list[str] | None = None,
    hints: dict[str, list[str]] | None = None,
) -> str:
    """``related`` holds select.Related items: related repos that stay closed."""
    related = related or []
    related_paths = {r.repo.path for r in related}
    lines = [
        "# Blind workspace (generated by blinders)",
        "",
        "This session started *blind*: this directory holds no source code, only this index.",
        "Do not guess file paths inside repos that are not opened.",
        "",
    ]
    if opened:
        where = "linked under this directory" if linked else "added to this session"
        lines += [f"## Opened repos ({where})"]
        for r in opened:
            lines.append(_line(r))
            if r.graph_report:
                lines.append(f"  code graph report (read before grepping): {r.graph_report}")
            lines += (hints or {}).get(r.name, [])
        lines += [""]
    else:
        lines += ["## Opened repos", "- none yet", ""]
    if related:
        lines += ["## Related repos (closed, likely relevant if the question widens)"]
        lines += [_line(r.repo, why=r.why) for r in related]
        lines += [""]
    rest = [r for r in closed if r.path not in related_paths]
    shown = rest[: cfg.index_max_closed]
    lines += ["## Closed repos (known, not visible)"]
    lines += [_line(r) for r in shown] or ["- none"]
    if len(rest) > len(shown):
        lines.append(f"- ... and {len(rest) - len(shown)} more (run `blind list`)")
    if mcp_dropped:
        lines += [
            "",
            "## MCP servers not loaded in this session",
            ", ".join(mcp_dropped),
            f"Ask the user to restart with `blind run {cli} --mcp <names>` if one is needed.",
        ]
    if skills_dropped:
        lines += [
            "",
            "## Skills hidden in this session",
            ", ".join(skills_dropped),
            f"The user can still run one by hand with `/<name>`, or restart with `blind run {cli} --skills <names>`.",
        ]
    lines += [
        "",
        "## Opening a closed repo",
        "Ask the user to run `/add-dir <path>` (Claude Code) or `/directory add <path>` (Gemini CLI),",
        "or to restart with `blind run <cli> -r <repo-name>` (Codex, Mistral Vibe).",
        "",
    ]
    return "\n".join(lines)


def create_session(
    opened: list[Repo],
    closed: list[Repo],
    cfg: Config,
    link: bool = False,
    related: list | None = None,
    mcp_dropped: list[str] | None = None,
    mcp_config: dict | None = None,
    cli: str = "<cli>",
    skills_dropped: list[str] | None = None,
    skills_settings: dict | None = None,
    gemini_settings: dict | None = None,
    hints: dict[str, list[str]] | None = None,
) -> Path:
    root = sessions_dir()
    root.mkdir(parents=True, exist_ok=True)
    # mkdtemp: unique name even for two launches in the same second, created owner-only (0700)
    session = Path(tempfile.mkdtemp(prefix=time.strftime("%Y%m%d-%H%M%S-"), dir=root))
    text = render_index(opened, closed, cfg, linked=link, related=related, mcp_dropped=mcp_dropped, cli=cli,
                        skills_dropped=skills_dropped, hints=hints)
    for name in CONTEXT_FILENAMES:
        (session / name).write_text(text, encoding="utf-8")
    if mcp_config is not None:
        # May contain tokens copied from the user's MCP config: owner-only.
        target = session / "mcp.json"
        fd = os.open(target, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(mcp_config, fh)
    if skills_settings is not None:
        (session / "skills-settings.json").write_text(json.dumps(skills_settings), encoding="utf-8")
    if gemini_settings is not None:
        (session / ".gemini").mkdir(exist_ok=True)
        (session / ".gemini" / "settings.json").write_text(json.dumps(gemini_settings), encoding="utf-8")
    if link:
        for repo in opened:
            target = session / repo.name
            if not target.exists():
                target.symlink_to(repo.path, target_is_directory=True)
    return session


def prune_sessions(cfg: Config, everything: bool = False) -> int:
    root = sessions_dir()
    if not root.is_dir():
        return 0
    cutoff = time.time() - cfg.session_ttl_days * 86400
    removed = 0
    for entry in root.iterdir():
        try:
            if entry.is_dir() and not entry.is_symlink() and (everything or entry.stat().st_mtime < cutoff):
                shutil.rmtree(entry)  # never follows symlinks: removes links, not their targets
                removed += 1
        except OSError:
            continue
    return removed
